Helsinki-Testbed
AvoinOrg/climate-map pull request #9
Opened 2022-12-05 13:19 UTC by tomtom7979

* Popup.tsx --> Code entity that calculates Apartment Buildings energy efficiency
* layerConf.ts --> Demolished buildings color to black

2022-12-12 11:48 UTC, xbexbex requested changes
Very good! Just a couple of minor nitpicks :)

2022-12-12 11:48 UTC, xbexbex commented on legacy/webpack.config.babel.js
> +    extensions: ['.webpack-loader.js', '.web-loader.js', '.loader.js', '.js', '.jsx', '.ts', '.tsx', '.json'],
What is this used for? I don't think you added json files anywhere.

2022-12-12 11:48 UTC, xbexbex commented on package.json
> +    "json-loader": "^0.5.7",
Same as above. Please remove the import if it not used.

2022-12-12 11:48 UTC, xbexbex commented on package.json
> +    "@babel/plugin-proposal-object-rest-spread": "^7.19.4",
What is this used for? Please remove the import if it not used.

2022-12-12 11:48 UTC, xbexbex commented on src/components/Map/Layers/Buildings/HelsinkiBuildings/Popup.tsx
> +var heatings
Could you change all the "var" declarations in the code to "const" if they don't change? And to "let" if they are redeclared.

2022-12-12 11:48 UTC, xbexbex commented on src/components/Map/Layers/Buildings/HelsinkiBuildings/Popup.tsx
> +// Estimated annual energy consumption [kWh/m3,a]
It seems a bit redundant to transform the JSON-string to javascript object every time the code is run. Could you pre-convert the json to object? You can use the console on any webpage to run this code and just paste the resulting object here.

Also, please split large constant objects to a "constants.ts"-file and export from there. See [https://github.com/AvoinOrg/climate-map/blob/ol/src/components/Map/Layers/Forests/FinlandMatureForests/constants.ts](https://github.com/AvoinOrg/climate-map/blob/ol/src/components/Map/Layers/Forests/FinlandMatureForests/constants.ts)

2022-12-15 08:03 UTC, tomtom7979 commented
Hi, I made changes and pushed the changes to ol-ti branch.

2022-12-15 12:53 UTC, merged